# ?? ??
server.port=8080
server.address=0.0.0.0

# MySQL DB ??
spring.datasource.url=jdbc:mysql://localhost:3306/auto_trading?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=KKH
spring.datasource.password=rla1rud1gH!

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
